# Generated by Django 5.1.3 on 2024-12-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime_of_payment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', to='core.orderitem'),
        ),
    ]
