# Generated by Django 5.1.3 on 2024-12-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_checkoutaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutaddress',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
